{% set version = '1.2-14' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrix
  version: {{ version|replace("-", "_") }}

source:
  fn: Matrix_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Matrix_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_{{ version }}.tar.gz
  sha256: 49a6403547b66675cb44c1afb04bb87130c054510cb2b94971435a826ab41396

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-lattice

  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('Matrix')"  # [not win]
    - "\"%R%\" -e \"library('Matrix')\""  # [win]

about:
  home: http://Matrix.R-forge.R-project.org/
  license: GPL (>= 2)
  summary: A rich hierarchy of matrix classes, including triangular, symmetric, and diagonal
    matrices, both dense and sparse and with pattern, logical and numeric entries.   Numerous
    methods for and operations on these matrices, using 'LAPACK' and 'SuiteSparse' libraries.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
