{% set version = "1.7-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-matrix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Matrix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Matrix/Matrix_{{ version }}.tar.gz
  sha256: a2cabbf04e4e2cafbd0a04281f130bb58e4f7653a91951368a404ef8682b38a1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]
  skip: true  # [r_base == "4.3"]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-lattice
    - libblas
    - liblapack
  run:
    - r-base
    - r-lattice

test:
  source_files:
    - tests/
  commands:
    - $R -e "library('Matrix')"           # [not win]
    - Rscript tests/Simple.R              # [not win]
    - "\"%R%\" -e \"library('Matrix')\""  # [win]
    - "Rscript tests/Simple.R"            # [win]

about:
  home: http://Matrix.R-forge.R-project.org/
  license: GPL-2.0-or-later
  summary: A rich hierarchy of sparse and dense matrix classes, including general, symmetric, triangular, and diagonal matrices with numeric, logical, or pattern entries. Efficient methods for operating on such matrices, often wrapping the 'BLAS', 'LAPACK', and 'SuiteSparse' libraries.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENCE

extra:
  recipe-maintainers:
    - conda-forge/r
