{% set version = "1.2-12" %}

package:
  name: r-matrix
  version: {{ version.replace("-", "_") }}

source:
  fn: Matrix_{{ version }}.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/Matrix_{{ version }}.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_{{ version }}.tar.gz
  sha256: 16e51aef69dca94dc4fcba8aa35a0039d9d0e6abd9cc017c095e954e1e2ca4f2

build:
  number: 0
  skip: True  # [win32]
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix  # [win64]
    - m2w64-toolchain  # [win64]
    - gcc  # [not win]
    - r-lattice
  run:
    - r-base
    - r-lattice

test:
  commands:
    - R -e "library('Matrix')"  # [not win]
    - R -e \"library('Matrix')\"  # [win]

about:
  home: http://Matrix.R-forge.R-project.org/
  license: GPL-2.0
  license_file: LICENCE
  summary: "Classes and methods for dense and sparse matrices and operations on them using 'LAPACK'
    and 'SuiteSparse'."

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
