appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: PfCnzpk+EFnSMfsCWHkedVeMrcSWCfu0xmujiE3EinMl9BVtpXgmw/TeH4OI/wAFeZStcp7Ai+tO0/LJ+6sja5ULd9wmQmQrnsG+WvdZsMvni0lFOWO/u9JOJjpWtHdE9pFhdFq1ZCFxw+ThvuRwzWXJvtu7DmfkSjn2WuHilHs8u7U8CgSS45Bd/XR1hNNszus0yEfIS4WsjiSNBr6BWnZuYEVPf2Gm5BWvSa3bi9zOSf5Dh+13O7nDTNL65cRvbuzYXlAqnYHFXy8VK92gM7BGWyM5EwR2jZ4twdf6wvTdZE7S/RJ2HoMW967UMVhOs8fgI6h8tDdlLIJsRx9FSfHfZNAtLGPLe/wQ1fRdy+wmiPSGyjBEcDUgX2X/mDh+fiW1ycaYRb6qCra2OWRT+nes8JN2Jvvn70h+vXJnOcbYEy6hSEXU0lFzSLY2VeESVc7jiDCr4QY5Kqr/0IGxiSB9ZIS6l6TuZGwX63tAsWSwIp5zVM09EWCP2UOvNqqHR2F8tAb82ztpC9SThHkCALKkoQMl+xjuO/omPG0qi6GEj0mG9K1iJB7+ulT1uDUKJltuDYruQjBIUwHXW+7sdyKSCYQPKwI6xbdteFm3TRwxUZm8VnAJockbtYO5mpQmy1156CpzaXKwOeDsNtAoInsoXEQF5ja19Q1B3O0ozrM=}
bot:
  automerge: true
